server:
  port: 8088
  servlet:
    context-path: /
    application-display-name: userService

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/gmall?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: user-service

mybatis:
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: user-service-8080
    prefer-ip-address: true
#    appname: user-service

info:
  app.name: user-service-8080
  app.descrption: 用户服务调用
  company.name: hmy
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'
debug: true
